name: mersenne
version: 1.1.0
homepage: https://github.com/damoti/mersenne
author: Lex Berezhny <lex@damoti.com>
description: >
    A Dart package for generating high-quality Mersenne Twister random numbers.

environment:
  sdk: '>=2.12.0 <3.0.0'
